// import type {Metadata} from "next";
import "./globals.css";

import {interRegular} from "./ui/fonts";
import Footer from "./ui/Footer";
// import {interBold, lalezar} from "./ui/fonts";
import NavBar from "./ui/NavBar";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interRegular.className} flex min-h-screen flex-col justify-between antialiased`}
      >
        <div className="mx-64">
          <NavBar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
